# Generated by Django 4.2.7 on 2026-03-01 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('target_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('dns_success', models.BooleanField(default=False)),
                ('dns_resolved_ips', models.JSONField(blank=True, default=list)),
                ('open_ports', models.JSONField(default=list)),
                ('overall_risk', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=20)),
                ('critical_ports_count', models.IntegerField(default=0)),
                ('high_ports_count', models.IntegerField(default=0)),
                ('medium_ports_count', models.IntegerField(default=0)),
                ('full_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target', '-created_at'], name='scanner_sca_target_485029_idx'), models.Index(fields=['overall_risk'], name='scanner_sca_overall_873d42_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('target_scanned', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.scanresult')),
            ],
            options={
                'verbose_name_plural': 'Scan History',
                'ordering': ['-created_at'],
            },
        ),
    ]
